### ISSUE TITLE
install-dev node version issues

### ISSUE THREAD

**Issue by jgunderson** [xtuple/xtuple-server-core#460]
Trying to setup up a vagrant provision script for a dev machine using install-dev.  See the script below.
When I don't set the node version I get:

```
==> default: WARN
==> default:  engine xtuple-linguist@0.1.1: wanted: {"node":"0.10.x"} (current: {"node":"0.11.13","npm":"1.5.0-alpha-4"})
==> default: npm 
==> default: WARN engine paynode@0.3.6: wanted: {"node":"~0.6.7"} (current: {"node":"0.11.13","npm":"1.5.0-alpha-4"})
==> default: 
==> default: > bcrypt@0.7.8 install /home/vagrant/dev/xtuple/node_modules/bcrypt
==> default: > node-gyp rebuild
==> default: make: Entering directory `/home/vagrant/dev/xtuple/node_modules/bcrypt/build'
==> default: make: 
==> default: Warning: File `bcrypt_lib.target.mk' has modification time 1.2 s in the future
==> default:   CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
==> default:   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
==> default:   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
==> default: ../src/bcrypt_node.cc: In destructor 'virtual {anonymous}::baton_base::~baton_base()':
==> default: ../src/bcrypt_node.cc:54:18: error: 'class v8::Persistent<v8::Function>' has no member named 'Dispose'
==> default: ../src/bcrypt_node.cc: At global scope:
==> default: ../src/bcrypt_node.cc:128:19: error: variable or field 'GenSaltAsync' declared void
==> default: ../src/bcrypt_node.cc:128:19: error: 'uv_work_t' was not declared in this scope
==> default: ../src/bcrypt_node.cc:128:30: error: 'req' was not declared in this scope
==> default: ../src/bcrypt_node.cc:137:24: error: variable or field 'GenSaltAsyncAfter' declared void
==> default: ../src/bcrypt_node.cc:137:24: error: 'uv_work_t' was not declared in this scope
==> default: ../src/bcrypt_node.cc:137:35: error: 'req' was not declared in this scope
==> default: ../src/bcrypt_node.cc:429:30: error: expected '}' at end of input
```
on the npm install for xtuple.  I think the bcrypt problem is due to using node 11.

So If I set node to 10 the xtuple npm install works but then install-dev fails:

```
207 error xtuple Command failed: cd /home/vagrant/dev/xtuple && sudo -u vagrant node /home/vagrant/dev/xtuple/scripts/build_app.js -c /home/vagrant/.xtuple/etc/xtuple/vagrant-470$
208 verbose xtuple [ 'Error: Command failed: cd /home/vagrant/dev/xtuple && sudo -u vagrant node /home/vagrant/dev/xtuple/scripts/build_app.js -c /home/vagrant/.xtuple/etc/xtuple$
208 verbose xtuple   '',
208 verbose xtuple   '    at checkExecSyncError (child_process.js:1330:13)',
208 verbose xtuple   '    at execSync (child_process.js:1370:13)',
208 verbose xtuple   '    at Object._.extend.buildCore (/usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-xt-database/index.js:159:5)',
208 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-xt-database/index.js:147:15',
208 verbose xtuple   '    at Function.forEach (/usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-xt-database/node_modules/lodash/dist/lodash.js:3297:15)',
208 verbose xtuple   '    at Object._.extend.executeTask (/usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-xt-database/index.js:146:7)',
208 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server/index.js:47:12',
208 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-lib/util.js:44:16',
208 verbose xtuple   '    at Function.forEach (/usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-lib/node_modules/lodash/dist/lodash.js:3297:15)',
208 verbose xtuple   '    at /usr/local/lib/node_modules/xtuple-server/node_modules/xtuple-server-lib/util.js:42:9' ]

```

```
# Bootstrap
wget git.io/hikK5g -qO- | sudo bash

# Clone repos first.  Have trouble with git ssh authorization after xtuple-server install-dev is run (why?)
cd /home/vagrant/dev
git clone https://github.com/xtuple/xtuple.git --recursive
git clone https://github.com/xtuple/xtuple-extensions.git
git clone https://github.com/xtuple/bi-open.git

# Install xtuple-server
npm install -g xtuple-server

# Install xtuple-extensions
sudo chmod -R 777 /usr/local/lib
#sudo n 0.10
cd xtuple-extensions
git submodule update --init --recursive --quiet
npm install --quiet
cd ..
  
# Install xtuple
cd xtuple
npm install --quiet
cd ..

# Use the server to do an install and build xtuple (must be in the xtuple folder?)
#sudo n 0.11
cd /home/vagrant
sudo xtuple-server install-dev --xt-demo --xt-adminpw admin --nginx-sslcnames 192.168.33.10 --local-workspace /home/vagrant/dev/xtuple

# Install BI and perform ETL
cd /home/vagrant/dev
sudo chmod -R 777 /usr/local/lib
#sudo n 0.10
cd bi-open/scripts
sudo -H bash build_bi.sh -eblm -c ../../xtuple/node-datasource/config.js -d demo_dev -P admin -n 192.168.33.10
cd ../..

# Install bi-open.
cd xtuple
sudo ./scripts/build_app.js -d demo_dev -e ../xtuple-extensions/source/bi_open
cd ..

# Start the servers.  This will run as an init.d on reboots
sudo service vagrant_init
```

**Comment by shackbarth** [comment]
We're using node 0.11 for the xtuple server because of reasons. It's a pain, I know. When you're doing stuff by hand in the app in the cli it's frequently important to check which version of node you're on.
